tasks:
  - name: Update settings.xml
    before: |
      cp .mvn/settings.xml ~/.m2/settings.xml
      cd $GITPOD_REPO_ROOT
  - name: selfupdate SDKMAN
    before: sdk selfupdate
  - name: select Maven 3.8.3
    before: sdk use maven 3.8.3
vscode:
  extensions:
    - bierner.markdown-preview-github-styles
    - github.vscode-pull-request-github
    - github.vscode-codeql
    - redhat.fabric8-analytics
    - redhat.java
    - redhat.vscode-commons
    - redhat.vscode-xml
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
