files:
  - source: '/src/main/resources/org/jenkinsci/plugins/schedulebuild/**/*.properties'
    ignore:
      - '/src/main/resources/org/jenkinsci/plugins/schedulebuild/**/%file_name%_%two_letters_code%.properties'
    translation: '/src/main/resources/org/jenkinsci/plugins/schedulebuild/**/%file_name%_%two_letters_code%.properties'

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
